### ISSUE TITLE
Resticted access for users

### ISSUE THREAD

**Issue by ramkrishna-babu** [SethRobertson/HowToPutGitOnTheWeb#1]
Hi,

Please let me know , is Git supports repository wise custom access to users over http.

Example.

For repository1

user1 should have R/W access
user2 should have R only access

other than 2 users nobody should have access to this repository.

**Comment by SethRobertson** [comment]
Using something like gitlab would provide an easy way of accomplishing this since they have everything packaged--performing the gradiated access control with a program is much easier than doing it from the web server. If you want to do it manually (similar to how I have suggested) then you will have to do some experimentation and testing.

It looks like setting the REMOTE_USER environmental variable is what controls, from the web server side, whether or not the user has read/write access.  It looks like we can control this using LDAP. So I would suggest using the AuthLDAPRemoteUserAttribute Directive.  Put both users in an LDAP group and follow the LDAP group instructions I gave on the website.  Then for the user who should have read/write access, create an LDAP attribute ONLY FOR HIM which provides his username.  The other user should not have this attribute.  Then when you add the AuthLDAPRemoteUserAttribute Directive, hopefully REMOTE_USER will only be set for the user with read/write access and not for the user with read-only access.  However, you should test this carefully since I did not.

Good luck, and please report back if you were successful.
